import { axiosInterceptor } from "./axios";

export const resgister=(userData)=> axiosInterceptor.post("/users/signup",userData)
export const login=(userData)=> axiosInterceptor.post("/users/signin",userData)
export const changePassword=(userData)=> axiosInterceptor.patch("/users/change-password",userData)
export const profileData=()=> axiosInterceptor.get("/users/profile-data")
export const getMyPosts=(userId)=> axiosInterceptor.get(`/users/${userId}/posts`)
export const getMySavedPosts=()=> axiosInterceptor.get("/users/bookmarks")
export const getFeedPosts=()=> axiosInterceptor.get("/posts/feed?only=following&limit=30")
export const getAllPosts=()=> axiosInterceptor.get("/posts")
export const getAllComments=(postId , page)=> axiosInterceptor.get(`/posts/${postId}/comments?page=${page}&limit=5`)
export const getPostDetails=(postId)=> axiosInterceptor.get(`/posts/${postId}`)
export const getPostLikes=(postId , page)=> axiosInterceptor.get(`/posts/${postId}/likes?page=${page}&limit=20`)
export const addPost=(postFormData)=> axiosInterceptor.post("/posts",postFormData)
export const savePost = (postId)=> axiosInterceptor.put(`/posts/${postId}/bookmark`)
export const likePost = (postId)=> axiosInterceptor.put(`/posts/${postId}/like`) 
export const deletePost = (postId)=> axiosInterceptor.delete(`/posts/${postId}`)
export const editPost = (postId , postData)=> axiosInterceptor.put(`/posts/${postId}`, postData)
export const addComment = (postId , commentData)=> axiosInterceptor.post(`/posts/${postId}/comments`, commentData)
export const likeComment = (postId, commentId)=> axiosInterceptor.put(`/posts/${postId}/comments/${commentId}/like`)
export const replyToComment = (postId, commentId, commentData) => axiosInterceptor.post(`/posts/${postId}/comments/${commentId}/replies`, commentData)
export const getCommentReplies = (postId, commentId, page) => axiosInterceptor.get(`/posts/${postId}/comments/${commentId}/replies?page=${page}&limit=10`)
export const followSuggestions = () => axiosInterceptor.get("/users/suggestions?limit=10")